from decouple import config

TEST_DATABASE_URL = config('TEST_DATABASE_URL')
DATABASE_URL = config('DATABASE_URL')
SECRET_KEY = config('SECRET_KEY')
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
